### ISSUE TITLE
Avoid `convert` to `Interval` in `^`

### ISSUE THREAD

**Issue by lbenet** [JuliaIntervals/IntervalArithmetic.jl#618] opened 2024-01-18 23:37 UTC
In current master:
```julia
julia> using IntervalArithmetic

julia> a = interval(1,2)
[1.0, 2.0]_com

julia> a^4
[1.0, 16.0]_com_NG
```
The *non-guaranteed* flag is disturbing. The problem arises from [these lines](https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/946493a03a1c4535334956302ec7a2c9807e0d59/src/intervals/arithmetic/power.jl#L63C1-L66C74), which use `convert`. This, incidentally, does not respects the `PowerMode` in use.

**Comment by dpsanders** [comment] 2024-01-18 23:49
A positive integer power should just be done by power by squaring, which ends up as repeated squaring and so should be guaranteed.

**Comment by dpsanders** [comment] 2024-01-18 23:50
I'm pretty sure I implemented that -- possibly in the fast powers work? 

I guess the issue is that this will not give correct rounding but only faithful rounding, but that seems better than having something that is not guaranteed.

**Comment by lbenet** [comment] 2024-01-18 23:56
As far as I tracked it, the problem is the `convert` itself:
```julia
julia> convert(Interval{Float64}, 4.0)
[4.0, 4.0]_com_NG
```

I don't think `power_by_squaring` is still there...

**Comment by lbenet** [comment] 2024-01-18 23:56
Note that `pow` and `pown` should have been used according to `PowerMode`

**Comment by lbenet** [comment] 2024-01-19 00:16
> I guess the issue is that this will not give correct rounding but only faithful rounding, but that seems better than having something that is not guaranteed.

The `NG` flag means (essentially) that a non-interval quantity (say an `Int`), or a conversion, or a function from the outside world (e.g., from `ForwardDiff`) has been used; some info in the docstrings of `isguaranteed`. This is an example:
```julia
julia> a = interval(1,2)
[1.0, 2.0]_com

julia> 4*a
[4.0, 8.0]_com_NG
```

**Comment by dpsanders** [comment] 2024-01-19 00:25
I see. I guess my point is that integers should always be exact and so should not be treated like this?

**Comment by dpsanders** [comment] 2024-01-19 00:27
I guess the reasoning is that the integer could be the result of a computation that led to overflow and so is not correct. But still, this seems wrong to me.

**Comment by lbenet** [comment] 2024-01-19 00:34
That is one possibility; another is having a very big integer such that its conversion to, say `Interval{Float64}`, is not exact. This was discussed in #594

**Comment by OlivierHnt** [comment] 2024-01-19 11:06
The power by squaring is still in the library, cf. https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/946493a03a1c4535334956302ec7a2c9807e0d59/src/intervals/arithmetic/power.jl#L343-L366

Also, I do think that the version on master calls `_select_pow()` correctly.

The *non-guaranteed* flag is deliberate (see also the conversation from PR https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/594).
Essentially, we can only faithfully guarantee an operation `x ^ n` if and only if both `x` and `n` are `Interval`, since, for instance, one can convert floats (which do not have correct rounding) to integers eg `Int(::AbstractFloat)`.

An other annoyance is the following

```Julia
julia> true * interval(1)
[1.0, 1.0]_com_NG
```

As above, one can do `Bool(::AbstractFloat)`...

So in my perspective, PR https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/619 makes things more confusing. Either we use a "guarantee" flag everywhere or we never do.

Now, there is an important difference with code where the exponent is explicitly typed in by the user (as in the OP), in which case I agree that having the non-guaranteed flag can be safely removed.
So the question is how to know whether the exponent was explicitly typed in or comes from a computation? Well we could use `Base.literal_pow`; e.g.

```Julia
julia> Base.literal_pow(::typeof(^), x::Interval, ::Val{n}) where {n} = x^interval(n)

julia> interval(1)^3
[1.0, 1.0]_com
```

Question: can constant propagation result in a call to `Base.literal_pow`? If it cannot, then I believe this is a good fix for this issue.

PS: of course one can preface their code with `@interval` to remove the non-guaranteed flag.

**Comment by lbenet** [comment] 2024-01-19 14:06
Thanks for clarifying about `IntervalArithmetic._positive_power_by_squaring`. Why I agree that this name is more appropriate now, should we address the negative integer powers too?

> Also, I do think that the version on master calls `_select_pow()` correctly.

You are perhaps right with regards to `_select_pow()` (since the idea of how are things in master is to evaluate `a^b` with both `a` and `b` both `Interval`s, so it is somewhere used), but the `convert` is the responsible for the "_NG" flag; #619 fixes this by simply using directly `_select_pow()` without creating the second interval. Why is that confusing? (Incidentally, this should be a bit faster.)

> Either we use a "guarantee" flag everywhere or we never do.

I'm not sure I follow you here. Since `a^4` returns an `Interval`, it does have the flag (fielname); using master it is set to `:false` and thus "_NG", while #619 has it`:true`.

> Now, there is an important difference with code where the exponent is explicitly typed in by the user (as in the OP), in which case I agree that having the non-guaranteed flag can be safely removed.

I agree we have to be extremely careful. Yet, the same can be argued when using `pow` or `pown`; using the default master:
```julia
# a complicated computation
julia> b = sqrt(16)
4.0

julia> a^b
[1.0, 16.0]_com_NG

julia> pow(a, b)
[1.0, 16.0]_com
```
with the latter has no "_NG" flag; #619 yields (in this case) the same result.

> So the question is how to know whether the exponent was explicitly typed in or comes from a computation? Well we could use `Base.literal_pow`

I have to think and play a little bit with `Base.literal_pow`. Currently in master, `Base.literal_pow(^, a, Val(4))` still returns the "_NG" flag, while in #619 the result is as expected (no "_NG" flag).

**Comment by OlivierHnt** [comment] 2024-01-19 14:59
I do sympathise with the issue though. It really depends what purpose we want the "NG" flag to serve.

Currently, its occurence symbolises "the interval may not be guaranteed: a non-interval number was involved in the computation which induced a potentially unsafe conversion".

As I understand it, the spirit behind #619 is to relaxe this statement to "the interval may not be guaranteed: a floating-point number was involved in the computation which induced a potentially unsafe conversion".
We assume integers are always safely computed despite the fact that one can generate them from floating-point computations, not to mention the problems with modular arithmetic.....

**Comment by lbenet** [comment] 2024-01-19 15:20
> I do sympathise with the issue though. It really depends what purpose we want the "NG" flag to serve.
> 
> Currently, its occurence symbolises "the interval may not be guaranteed: a non-interval number was involved in the computation which induced a potentially unsafe conversion".
> 
> As I understand it, the spirit behind #619 is to relaxe this statement to "the interval may not be guaranteed: a floating-point number was involved in the computation which induced a potentially unsafe conversion". We assume integers are always safely computed despite the fact that one can generate them from floating-point computations, not to mention the problems with modular arithmetic.....

While I think I agree (and understand) the meaning of "NG", I am not sure if #619 implies relaxing a "non-interval number" into a "floating point"... but I see your point.

**Comment by OlivierHnt** [comment] 2024-01-19 15:28
Oops I should have made this more clear that it's not on master: one needs to overload `Base.literal_pow` to fix the issue described in the OP, ie `x ^ 4`, while keeping the NG flag for `x ^ n` (even if `n` is an integer).


I wish I had a good example to illustrate my concerns 🙁. All I can come up with right now is the following:
```Julia
int = floatmax(Float64)
wrong_int = int - 1 # still equals `int`
x ^ Int(wrong_int) # should have the NG flag
```

**Comment by lbenet** [comment] 2024-01-19 17:18
First, let me explain the context that led me to propose #619, which is https://github.com/JuliaDiff/TaylorSeries.jl/pull/345, where I try to accomodate to the new functionality/requirements of IntervalArithmetic. There, one either has polynomials with interval coefficients, or evaluates polynomials (with interval or non-interval numeric coefficients) in intervals. (TaylorModels.jl uses this, and computes a bound, to rigorously bound functions, but I haven't come that far.) In any case, I need to evaluate expressions such as $x^4$, and it is confortable to not require the user to give the expression using `pown`; I think this is a generic situation (for IA) since we want to allow the user to define Julia functions using functions such as `+` or `cos`, and I think `^`as well. Hence #619. Once said this, your rematk about `literal_pow` could indeed be very useful.

**Comment by lbenet** [comment] 2024-01-19 17:21
> I wish I had a good example to illustrate my concerns 🙁.

Not sure if the following is a good example, but it illustrates a deeper problem (I'm on master, but expect the same problems in 071b285 --except for the NG flag--, since the issue is directly concerned with `BareInterval`s):
```julia
# First, let me note that the floating point result corresponds to a different tinteger result in exact arithmetic, 
# though they are the same in floating-point arithmetic (or converting the floating-point number to an Int)
julia> 2^55, 2.0^55
(36028797018963968, 3.602879701896397e16)

julia> prevfloat(2.0^55)
3.6028797018963964e16

# Note that the actual intervals returned (bareintervals) in the next checks do not contain the 
# correct integer in the answer; in the next case, the NG is ok
julia> interval(2)^55
Interval{Float64}(3.602879701896397e16, 3.602879701896397e16, com, NG)

# Same as above, including the NG flag
julia> Base.literal_pow(^, interval(2), Val(55))
Interval{Float64}(3.602879701896397e16, 3.602879701896397e16, com, NG)

# AUCH: no NG flag and the bareinterval is wrong
julia> interval(2)^interval(55)
Interval{Float64}(3.602879701896397e16, 3.602879701896397e16, com)

# And the problem lies deep inside!
julia> bareinterval(2)^bareinterval(55)
BareInterval{Float64}(3.602879701896397e16, 3.602879701896397e16)
```

**Comment by OlivierHnt** [comment] 2024-01-20 00:30
Oh aren't they actually the exact same integers? `2^55 == 2.0^55` holds, which means `3.602879701896397e16` may be a display "issue", similar to how `0.1` is a float very close to 1/10.

**Comment by lbenet** [comment] 2024-01-20 00:40
CMaybe you are right... and it is a display issue. I'll think of a better example...

**Comment by lbenet** [comment] 2024-01-26 18:00
> Oh aren't they actually the exact same integer? `2^55 == 2.0^55` holds, which means 3`.602879701896397e16` may be a display "issue", similar to how `0.1` is a float very close to 1/10.

Just to settled this, I checked it using `bitstring`: `2^55 == 2.0^55` is indeed true, because the mantisa of 2.0^55 is (1.)0...0 as it should. So it is indeed a display issue.

**Comment by dpsanders** [comment] 2024-01-26 19:36
I'm not sure if I totally follow the discussion but
```
julia> 2.0^55 + 1 == 2.0^55
true
```

Beyond `2.0^52`, multiple integers are represented by the *same* Float64.

**Comment by OlivierHnt** [comment] 2024-01-26 20:00
```Julia
julia> eps(2.0^55)
8.0
```
So indeed `2.0^55 + 1` gives you back `2.0^55` (at least in double precision). I used this property in my example above to produce a non-rigorous integer.

On the other hand, Luis noticed is that `2^55` and `2.0^55` are actually the same integers but they are displayed differently in the REPL. Perhaps there is room for improvement, but that's on Julia's side.

**Comment by dpsanders** [comment] 2024-01-26 20:23
I believe that the display of a float chooses the shortest representation that gives the same float, so I think that's what's happening here.

**Closed** 2024-01-31 23:01 UTC
