### ISSUE TITLE
Arithmetic with numbers of different types should be defined

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#389] opened 2020-06-09 20:00 UTC
```jl
julia> X = 3..4
[3, 4]

julia> @which X / 3.1
/(a::Interval{T}, x::T) where T<:Real in IntervalArithmetic at /home/dpsanders/.julia/dev/IntervalArithmetic/src/intervals/arithmetic.jl:150

julia> @which X / Float32(3.1)
/(x::Number, y::Number) in Base at promotion.jl:314
```

The version with `Float32` falls back to the `Base` promotion mechanism, so will promote to an interval instead of using the optimized division by a scalar.

**Comment by lbenet** [comment] 2020-06-09 20:42
I think the problem is not `Float32` by itself; the method applies to `a::Interval{T}` and `x::T`, i.e., `X` in your example should also be `Interval{Float32}` (and not `Interval{Float64}`) in order to use the method.

**Comment by dpsanders** [comment] 2020-06-09 20:54
Yes exactly, I mean that we should define e.g.
```jl
/(x::Interval{T}, y::S<:Real)
```
where `S` is *not* equal to `T`.

**Comment by dpsanders** [comment] 2020-06-09 20:55
i.e I need to be able to divide an `Interval{Float64}` by a `Float32`.

**Comment by OlivierHnt** [comment] 2023-07-24 18:12
Fixed on master.

**Closed by OlivierHnt** 2023-07-24 18:12 UTC
