### ISSUE TITLE
Performance discrepancy between powers of `Real` and `Complex` numbers

### ISSUE THREAD

**Issue by OlivierHnt** [JuliaIntervals/IntervalArithmetic.jl#501] opened 2021-12-23 13:56 UTC
While using `abs` the other day, I found out the following difference (Julia v1.7.0, IntervalArithmetic v0.20.2):

```Julia
julia> using IntervalArithmetic, BenchmarkTools

julia> x = @interval(π + im*π)
[3.14159, 3.1416] + [3.14159, 3.1416]im

julia> @btime real($x)^2;
  5.284 μs (53 allocations: 2.27 KiB)

julia> @btime $x^2;
  299.747 ns (0 allocations: 0 bytes)
```

For powers of a `Real` number, there is a promotion to `Interval{BigFloat}` via `IntervalArithmetic.bigequiv` which does not seem to occur for `Complex{Interval{Float64}}`.

I am wondering what is the stand on this? In particular, if the goal is to yield the tightest possible interval (at the cost of performance), then perhaps it would be useful to control this behaviour via `setrounding`?

**Comment by lucaferranti** [comment] 2021-12-23 14:52
You are right, power of complex interval uses power by squaring, while power of real intervals goes for the tightest. I think #388 addresses this, isn't it so @dpsanders ?

**Comment by OlivierHnt** [comment] 2021-12-29 11:44
Thank you, I did not know about this PR. Indeed, it does seem to be a fix for this issue.

**Comment by OlivierHnt** [comment] 2022-04-12 15:49
@lucaferranti do you know what is the state of #388?

**Comment by lucaferranti** [comment] 2022-04-12 19:10
**Disclaimer**: This answer is based on what I remember discussing with @dpsanders a while back and hence it is not necessarily accurate and would be good if David himself confirmed what I said.

That being said, my understanding is that that branch is basically working and it isn't merged yet because it is missing tests and docs. Hence I think you should be able to use that branch without too much fear (I can rebase it tomorrow)

That is indeed a very nice branch, since often it is preferred to prioritize speed over tightness and I definitely agree it would be good to get it merged and released, I can try to push it forward :)

**Comment by OlivierHnt** [comment] 2022-04-12 20:50
Thanks for your feedback. Great to hear! 🙂
The proposed `configure!` workflow would definitely comes in handy as currently one resorts to type piracy 😢.

**Closed** 2023-12-13 12:34 UTC
