### ISSUE TITLE
Possible bug in powers

### ISSUE THREAD

**Issue by AnderGray** [JuliaIntervals/IntervalArithmetic.jl#441] opened 2021-03-04 20:21 UTC
If `x = [-1,1], y = [-1,1]`

The program gives me `x^y => [0, Inf]`.

But `(-1)^(-1) = -1`, which is lower than 0.

Is my understanding wrong, but I think -1 should be in the result.

Cheers,
A

**Comment by dpsanders** [comment] 2021-03-04 20:33
Real (nonintever) powers of negative numbers are undefined, so the input interval is truncated to 0.

**Comment by dpsanders** [comment] 2021-03-04 20:35
What is the context in which this calculation occurs?

**Comment by lbenet** [comment] 2021-03-04 20:54
Maybe it is indeed a bug, but a problem arises with `0^(-1)`...

**Comment by AnderGray** [comment] 2021-03-04 20:57
Cool, thanks. 

I'm just computing powers of intervals, the truncation works for me. I guess it could return something imaginary in some situations?

**Comment by AnderGray** [comment] 2021-03-04 20:58
I like how the empty set is returned for 1/0

**Comment by lbenet** [comment] 2021-03-04 21:01
I guess the correct result should be `[-Inf, Inf]`, so it seems it is indeed a bug

**Comment by dpsanders** [comment] 2021-03-04 21:53
It can't return complex numbers since that would be type-unstable. That's the same reason that Julia does not do this:
```jl
julia> (-1.0)^-2.1
ERROR: DomainError with -1.0:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
Stacktrace:
 [1] throw_exp_domainerror(x::Float64)
   @ Base.Math ./math.jl:37
 [2] ^(x::Float64, y::Float64)
   @ Base.Math ./math.jl:901
 [3] top-level scope
   @ REPL[6]:1
```

**Comment by dpsanders** [comment] 2021-03-04 21:57
I think whether to include negative numbers is just a choice, not a bug.

**Comment by lbenet** [comment] 2021-03-05 20:24
I think the chose to *not* include negative numbers: https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/b70940dabdbefd8eb4be32d7bde6df72174dd3f7/src/intervals/functions.jl#L209-L211

If I recall correctly, we simply avoided the cases like `(-1)^(0.5)`.

**Comment by Kolaru** [comment] 2021-03-05 23:48
Let's ask our beloved standard (p. 20):
![image](https://user-images.githubusercontent.com/17861033/110186286-064c2a80-7e15-11eb-8874-0c45623b198b.png)

So basically we can do whatever we want when some input are outside the domain of the point function.

It may actually be a good use case for a decorated interval, since if I remember correctly they should track that kind of things and be able to tell something strange happened there. I'm not sure if it has been fully implemented yet though.

**Comment by dpsanders** [comment] 2021-03-06 00:04
Yes, I agree on both points. 
This is, in fact, already implemented:

```jl
julia> using IntervalArithmetic

julia> @format true;   # show decdorations

julia> x = DecoratedInterval(-1..1)
[-1, 1]_com

julia> x^x
[0, ∞]_trv   
```

`trv` means "something may have happened", for example the truncation of the domain that did actually happen!

**Comment by OlivierHnt** [comment] 2023-12-01 23:56
I believe we can close this, now that decorations are the default #590.

**Closed by OlivierHnt** 2023-12-01 23:56 UTC
